server:
  port: ${SERVER_PORT}
  forward-headers-strategy: ${FORWARD_HEADERS_STRATEGY:none}

keycloak:
  realm: ${KEYCLOAK_REALM}
  host: ${KEYCLOAK_HOST}

postgres:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  database: ${POSTGRES_DATABASE}
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}

db:
  ddl-auto: ${DB_DDL_AUTO}

reuqest-timeout: ${REQUEST_TIMEOUT}

storage:
  max-file-size: ${MAX_FILE_SIZE}
  max-request-size: ${MAX_REQUEST_SIZE}
  file-system:
    location: ${STORAGE_LOCATION}
