server:
  port: ${SERVER_PORT}

keycloak:
  realm: ${KEYCLOAK_REALM}
  host: ${KEYCLOAK_HOST}
  client:
    user-api:
      client-id: ${KEYCLOAK_CLIENT_ID}
      client-secret: ${KEYCLOAK_CLIENT_SECRET}

postgres:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  database: ${POSTGRES_DATABASE}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

db:
  ddl-auto: none

reuqest-timeout: ${REQUEST_TIMEOUT}

storage:
  max-file-size: ${MAX_FILE_SIZE}
  max-request-size: ${MAX_REQUEST_SIZE}
  file-system:
    location: ${STORAGE_LOCATION}